"""Advisory Summary (officer + admin): ONE consolidated, downloadable advisory for
a district — seasonal risk, price outlook, disease alerts and an input plan — all
generated by the same answer() engine that powers the chat/SMS/WhatsApp, so every
figure in the download matches the live tools (single source of truth).
"""
from _ui import setup
from _i18n import t
import streamlit as st
import pandas as pd

from config.settings import DISTRICTS
from src.channels.whatsapp_bot import answer

setup("Advisory Summary", "One consolidated advisory to download and share",
      allowed_roles=("officer", "super_admin"))

CROPS = ["maize", "beans", "potatoes"]
RW_CROP = {"maize": "ibigori", "beans": "ibishyimbo", "potatoes": "ibirayi"}
rw = st.session_state.get("lang") == "rw"

c1, c2, c3 = st.columns(3)
district = c1.selectbox(t("District"), DISTRICTS)
land = c2.number_input(t("Land size (ha)"), 0.0, 20.0, 1.0, 0.5)
budget = c3.number_input(t("Budget (RWF)"), 0, 1_000_000, 80_000, 10_000)


def _q(kind, crop=None):
    """Build a query in the current language so answer() replies in it."""
    words = {"price": ("price", "igiciro"), "risk": ("risk", "ibyago"),
             "disease": ("disease", "indwara"), "input": ("fertilizer", "ifumbire")}
    word = words[kind][1] if rw else words[kind][0]
    cn = (RW_CROP[crop] if rw else crop) if crop else ""
    tail = f" {land:g} ha {int(budget)}" if kind == "input" else ""
    return f"{cn} {word} {district}{tail}".strip()


if st.button(t("Generate advisory"), type="primary"):
    with st.spinner(t("Building advisory…")):
        p = [f"AgriRisk — {t('Consolidated advisory')}",
             f"{t('Generated')}: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}",
             f"{t('District')}: {district}", ""]
        p += [f"=== {t('SEASONAL RISK')} ===", answer(_q('risk')), ""]
        p += [f"=== {t('PRICE OUTLOOK')} ==="] + [answer(_q('price', c)) for c in CROPS] + [""]
        p += [f"=== {t('DISEASE (next 14 days)')} ===", answer(_q('disease')), ""]
        if land and land > 0:
            p += [f"=== {t('INPUT PLAN')} ({land:g} ha) ==="] + [answer(_q('input', c)) for c in CROPS] + [""]
        p.append(t("This is an estimate with a stated margin of error. The decision stays with "
                   "the farmer; confirm with local conditions."))
        st.session_state["_advisory"] = "\n".join(p)

if st.session_state.get("_advisory"):
    summary = st.session_state["_advisory"]
    st.markdown(f"#### {t('Advisory preview')}")
    # Render as a clean, printable document card (bold green section headers)
    import html as _html, re as _re
    doc = _html.escape(summary)
    doc = _re.sub(r"AgriRisk — (.+)", r"<div class='ad-title'>AgriRisk — \1</div>", doc, count=1)
    doc = _re.sub(r"=== (.+?) ===", r"<div class='ad-sec'>\1</div>", doc)
    st.markdown(
        "<style>"
        ".advisory-doc{background:#fff;border:1px solid #DED7C4;border-radius:16px;"
        "padding:24px 28px;max-height:480px;overflow:auto;white-space:pre-wrap;"
        "font-family:'Poppins',sans-serif;font-size:13.5px;line-height:1.7;color:#1C2A22;"
        "box-shadow:0 10px 30px rgba(27,67,50,.07);}"
        ".advisory-doc .ad-title{font-weight:700;font-size:16px;color:#1B4332;margin-bottom:4px;}"
        ".advisory-doc .ad-sec{font-weight:700;color:#2D6A4F;letter-spacing:.04em;"
        "margin:14px 0 2px;padding-top:10px;border-top:1px solid #EDE7D8;}</style>"
        f"<div class='advisory-doc'>{doc}</div>", unsafe_allow_html=True)
    st.download_button(
        t("Download advisory summary"), data=summary.encode("utf-8"),
        file_name=f"agririsk_advisory_{district}_{pd.Timestamp.now().strftime('%Y-%m-%d')}.txt",
        mime="text/plain", icon=":material/download:", type="primary")
    st.caption(t("Generated by the same engine as the chat, SMS and WhatsApp, so the figures match."))