"""Build an EXECUTED Jupyter notebook for the AgriRisk Rwanda models.

Runs each code cell, captures stdout and matplotlib figures, and writes a
nbformat-v4 .ipynb with embedded outputs (so it renders on GitHub). Also saves
figures to reports/figures/ and serializes trained models to models_store/.

Run:  PYTHONPATH=. python scripts/build_notebook.py
"""
from __future__ import annotations

import base64
import contextlib
import io
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "notebooks" / "AgriRisk_Rwanda_Models.ipynb"
FIGDIR = ROOT / "reports" / "figures"
FIGDIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------- cell content
CELLS: list[tuple[str, str]] = []
def md(text: str): CELLS.append(("markdown", text.strip("\n")))
def code(text: str): CELLS.append(("code", text.strip("\n")))

md(r"""
# AgriRisk Rwanda — ML Models Notebook

**AI-powered agricultural risk management for smallholder farmers in Rwanda.**

This notebook covers the machine-learning core of the platform:

1. **Data visualization & engineering** — distributions, time-series, correlations, feature engineering
2. **Model architecture** — Random Forest & Gradient Boosting risk classifier; price-forecast baseline; production models (Prophet / ARIMA / LSTM) described
3. **Performance metrics** — accuracy, precision, recall, F1, confusion matrix (risk); MAPE (price)
4. **Deployment** — the Streamlit MVP that consumes these models

> **Data note.** This notebook runs on realistic **sample** datasets generated by
> `scripts/generate_sample_data.py`, calibrated to the figures in the proposal
> (≈22% food inflation, ≈40% fertilizer surge). To use the real data, drop the
> WFP / FRED / HDX / World Bank files into `data/raw/` (see `data/README.md`) —
> no other code changes are needed.
""")

code(r"""
import warnings; warnings.filterwarnings("ignore")
import numpy as np, pandas as pd
import matplotlib.pyplot as plt, seaborn as sns
sns.set_theme(style="whitegrid", palette="deep")
from pathlib import Path
RAW = Path("..") / "data" / "raw"
if not (RAW / "wfp_food_prices_rwanda.csv").exists():
    RAW = Path("data") / "raw"   # fallback if run from project root

prices = pd.read_csv(RAW/"wfp_food_prices_rwanda.csv", parse_dates=["date"])
cpi    = pd.read_csv(RAW/"rwanda_food_cpi.csv", parse_dates=["date"]).sort_values("date")
fert   = pd.read_csv(RAW/"fertilizer_price_index.csv", parse_dates=["date"]).sort_values("date")
rain   = pd.read_csv(RAW/"district_rainfall_anomalies.csv", parse_dates=["date"]).sort_values("date")
inputs = pd.read_csv(RAW/"minagri_input_prices.csv")
print("Loaded datasets:")
for name, df in [("prices",prices),("cpi",cpi),("fertilizer",fert),("rainfall",rain),("inputs",inputs)]:
    print(f"  {name:11} {df.shape[0]:>5} rows x {df.shape[1]} cols")
""")

md("## 1. Data overview")
code(r"""
print("Crops:", sorted(prices.crop.unique()))
print("Markets:", sorted(prices.market.unique()))
print("Price date range:", prices.date.min().date(), "->", prices.date.max().date())
prices.head()
""")

md("## 2. Data visualization\n### 2.1 Crop price distributions")
code(r"""
fig, axes = plt.subplots(1, 2, figsize=(13,4.5))
sns.boxplot(data=prices, x="crop", y="price_rwf", ax=axes[0])
axes[0].set_title("Price distribution by crop (RWF/kg)"); axes[0].set_xlabel(""); axes[0].set_ylabel("RWF/kg")
for crop in prices.crop.unique():
    sns.kdeplot(prices[prices.crop==crop]["price_rwf"], label=crop, ax=axes[1], fill=True, alpha=.25)
axes[1].set_title("Price density by crop"); axes[1].set_xlabel("RWF/kg"); axes[1].legend()
plt.tight_layout()
""")

md("### 2.2 Price seasonality and trend")
code(r"""
maize = (prices[prices.crop=="maize"].groupby("date")["price_rwf"].mean())
beans = (prices[prices.crop=="beans"].groupby("date")["price_rwf"].mean())
potato= (prices[prices.crop=="potatoes"].groupby("date")["price_rwf"].mean())
plt.figure(figsize=(13,4.5))
plt.plot(maize.index, maize.values, label="maize")
plt.plot(beans.index, beans.values, label="beans")
plt.plot(potato.index, potato.values, label="potatoes")
plt.title("National average weekly crop prices (sample data)")
plt.ylabel("RWF/kg"); plt.legend(); plt.tight_layout()
""")

md("### 2.3 Food CPI and global fertilizer index\nThe 2022–23 spikes reproduce the proposal's documented ≈22% food inflation and ≈40% fertilizer surge.")
code(r"""
cpi["cpi_change"]  = cpi["food_cpi"].pct_change(12)*100
fert["fert_change"]= fert["fert_index"].pct_change(12)*100
fig, ax = plt.subplots(1, 2, figsize=(13,4.5))
ax[0].plot(cpi.date, cpi.food_cpi, color="darkred"); ax[0].set_title("Food CPI index")
ax[0].axvspan(pd.Timestamp("2022-01-01"), pd.Timestamp("2023-06-01"), color="red", alpha=.08)
ax[1].plot(fert.date, fert.fert_index, color="darkblue"); ax[1].set_title("Global fertilizer price index")
ax[1].axvspan(pd.Timestamp("2021-06-01"), pd.Timestamp("2023-06-01"), color="blue", alpha=.08)
plt.tight_layout()
print(f"Food CPI YoY peak:    {cpi.cpi_change.max():.1f}%")
print(f"Fertilizer YoY peak:  {fert.fert_change.max():.1f}%")
""")

md("## 3. Data engineering — building the seasonal-risk training set\nMerge rainfall anomalies with food-CPI and fertilizer YoY change, then label High/Medium/Low using the proposal's thresholds.")
code(r"""
def label_risk(rain_a, cpi_c, fert_c):
    if rain_a < -0.8 and (cpi_c > 15 or fert_c > 30): return "High"
    if rain_a < -0.3 or cpi_c > 10 or fert_c > 20:    return "Medium"
    return "Low"

risk = pd.merge_asof(rain, cpi[["date","cpi_change"]], on="date")
risk = pd.merge_asof(risk, fert[["date","fert_change"]], on="date").dropna().reset_index(drop=True)
risk["risk_level"] = risk.apply(lambda r: label_risk(r.rainfall_anomaly, r.cpi_change, r.fert_change), axis=1)
print("Risk dataset:", risk.shape[0], "rows")
print(risk["risk_level"].value_counts())
risk.head()
""")

code(r"""
plt.figure(figsize=(6,4))
order = ["Low","Medium","High"]
sns.countplot(data=risk, x="risk_level", order=order, palette=["#2e7d32","#f9a825","#c62828"])
plt.title("Seasonal risk class distribution"); plt.xlabel(""); plt.tight_layout()
""")

md("### 3.1 Feature correlations")
code(r"""
feat_cols = ["rainfall_anomaly","cpi_change","fert_change"]
corr = risk[feat_cols].corr()
plt.figure(figsize=(5.5,4.5))
sns.heatmap(corr, annot=True, cmap="vlag", center=0, fmt=".2f", square=True)
plt.title("Risk feature correlation matrix"); plt.tight_layout()
""")

md(r"""
## 4. Model architecture — seasonal risk classifier

Two ensemble classifiers are compared on three features
(`rainfall_anomaly`, `cpi_change`, `fert_change`):

- **Random Forest** — 100 trees, balanced class weights, Gini split criterion.
- **Gradient Boosting** — 100 stages, learning rate 0.1, log-loss objective.
  *(In the full environment this is XGBoost; scikit-learn's GradientBoosting is the
  offline stand-in here — both are gradient-boosted tree ensembles.)*

Split: stratified 80/20. Small Gaussian **observation noise** is added to the
features the model sees, reflecting real measurement error (otherwise the
rule-derived labels would be trivially recoverable).
""")
code(r"""
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

rng = np.random.default_rng(0)
X = risk[feat_cols].copy()
X["rainfall_anomaly"] += rng.normal(0, 0.15, len(X))
X["cpi_change"]       += rng.normal(0, 1.0,  len(X))
X["fert_change"]      += rng.normal(0, 2.0,  len(X))
y = risk["risk_level"]

Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
rf = RandomForestClassifier(n_estimators=100, class_weight="balanced", random_state=42).fit(Xtr, ytr)
gb = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42).fit(Xtr, ytr)
print("Trained Random Forest and Gradient Boosting classifiers.")
print("Train/test sizes:", len(Xtr), "/", len(Xte))
""")

md("## 5. Performance metrics")
code(r"""
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, classification_report, confusion_matrix)
def scores(model, name):
    p = model.predict(Xte)
    return {"model":name,
            "accuracy":  accuracy_score(yte,p),
            "precision": precision_score(yte,p,average="macro",zero_division=0),
            "recall":    recall_score(yte,p,average="macro",zero_division=0),
            "macro_f1":  f1_score(yte,p,average="macro")}
results = pd.DataFrame([scores(rf,"Random Forest"), scores(gb,"Gradient Boosting")]).set_index("model")
print(results.round(3).to_string())
print("\nTarget: accuracy > 0.85  ->", "MET" if results.accuracy.max() > 0.85 else "NOT MET")
print("\nBest model classification report (Random Forest):")
print(classification_report(yte, rf.predict(Xte), zero_division=0))
""")

code(r"""
cm = confusion_matrix(yte, rf.predict(Xte), labels=["Low","Medium","High"])
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Greens",
            xticklabels=["Low","Medium","High"], yticklabels=["Low","Medium","High"])
plt.title("Confusion matrix — Random Forest"); plt.ylabel("Actual"); plt.xlabel("Predicted"); plt.tight_layout()
""")

code(r"""
imp = pd.Series(rf.feature_importances_, index=feat_cols).sort_values()
plt.figure(figsize=(6,3.2))
imp.plot.barh(color="#2e7d32")
plt.title("Feature importance — Random Forest risk classifier"); plt.tight_layout()
""")

md(r"""
## 6. Crop price forecasting

### Production models (run with the full environment)
The platform compares three forecasters for 4-week-ahead prices:

- **ARIMA(p,d,q)** — statistical baseline on the price series alone.
- **Facebook Prophet** — additive decomposition (trend + yearly seasonality +
  changepoints) with **food CPI** and **fertilizer index** as extra regressors.
- **LSTM** — single recurrent layer of 50 units over a 12-week sliding window;
  `tanh`/`sigmoid` gate activations, **Adam** optimizer, MSE loss, linear output.

Below is a fully-runnable **baseline** (lag-feature Random Forest regressor) that
demonstrates the forecasting pipeline and the MAPE metric offline. Prophet/ARIMA/LSTM
code lives in `src/models/price_forecasting.py`.
""")
code(r"""
from sklearn.ensemble import RandomForestRegressor
def mape(yt, yp): return float(np.mean(np.abs((yt-yp)/yt))*100)

s = (prices[(prices.crop=="maize") & (prices.market=="Bugesera")]
     .sort_values("date").set_index("date")["price_rwf"])
d = pd.DataFrame({"y": s})
for lag in [1,2,3,4,8,12,52]:
    d[f"lag{lag}"] = d["y"].shift(lag)
d["target"] = d["y"].shift(-4)          # 4 weeks ahead
d = d.dropna()
cut = int(len(d)*0.8)
feats = [c for c in d.columns if c.startswith("lag")]
reg = RandomForestRegressor(n_estimators=200, random_state=42).fit(d[feats][:cut], d["target"][:cut])
pred = reg.predict(d[feats][cut:])
m = mape(d["target"][cut:].values, pred)
print(f"Maize / Bugesera 4-week-ahead baseline MAPE: {m:.2f}%   (target < 15%)")

idx = d.index[cut:]
plt.figure(figsize=(13,4.5))
plt.plot(idx, d["target"][cut:].values, label="actual", linewidth=2)
plt.plot(idx, pred, label="predicted (4wk ahead)", linestyle="--")
plt.title("Maize price forecast — hold-out test set (Bugesera)")
plt.ylabel("RWF/kg"); plt.legend(); plt.tight_layout()
""")

md(r"""
## 7. Persist models for the MVP
The dashboard loads these serialized artefacts at startup.
""")
code(r"""
import pickle
root = Path("..") if Path("../data/raw").exists() else Path(".")
store = root / "models_store"
store.mkdir(exist_ok=True)
with open(store/"risk_classifier.pkl","wb") as f: pickle.dump(rf, f)
with open(store/"price_baseline.pkl","wb") as f: pickle.dump(reg, f)
print("Saved: risk_classifier.pkl, price_baseline.pkl ->", store)
""")

md(r"""
## 8. Deployment — the MVP

The trained models are served through a **Flask web app** (`webapp/`): a custom dashboard
for extension officers plus a farmer-facing WhatsApp chatbot preview, covering all 30 districts.

```bash
python webapp/app.py     # then open http://localhost:5000
```

**Screens:** Home · Price Forecast · Seasonal Risk · Disease Alert · Input Recommender · WhatsApp Preview.

### Summary of results
| Module | Model | Metric | Target |
|--------|-------|--------|--------|
| Seasonal risk | Random Forest | accuracy (see §5) | > 85% |
| Price forecast | RF baseline | MAPE (see §6) | < 15% |

**Next steps:** swap the sample data for the real WFP / FRED / HDX / World Bank files;
train the production Prophet & LSTM forecasters in the full environment; add live WhatsApp
(Twilio) and SMS (Africa's Talking) delivery for farmers.
""")

# ----------------------------------------------------------------- execute + build
def split_lines(text: str):
    lines = text.splitlines(keepends=True)
    return lines if lines else [""]

ns: dict = {}
nb_cells = []
exec_count = 0
fig_i = 0
for ctype, src in CELLS:
    if ctype == "markdown":
        nb_cells.append({"cell_type": "markdown", "metadata": {}, "source": split_lines(src)})
        continue
    exec_count += 1
    outputs = []
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        try:
            exec(src, ns)
        except Exception as e:  # surface errors instead of failing silently
            print(f"!! ERROR: {type(e).__name__}: {e}")
    text = buf.getvalue()
    if text.strip():
        outputs.append({"output_type": "stream", "name": "stdout", "text": split_lines(text)})
    for num in plt.get_fignums():
        fig = plt.figure(num)
        png = io.BytesIO(); fig.savefig(png, format="png", bbox_inches="tight", dpi=110)
        b64 = base64.b64encode(png.getvalue()).decode()
        fig.savefig(FIGDIR / f"fig_{fig_i:02d}.png", bbox_inches="tight", dpi=110)
        fig_i += 1
        outputs.append({"output_type": "display_data", "data": {"image/png": b64}, "metadata": {}})
        plt.close(num)
    nb_cells.append({"cell_type": "code", "execution_count": exec_count,
                     "metadata": {}, "outputs": outputs, "source": split_lines(src)})

notebook = {
    "cells": nb_cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10"},
    },
    "nbformat": 4, "nbformat_minor": 5,
}
OUT.parent.mkdir(exist_ok=True)
OUT.write_text(json.dumps(notebook, indent=1))
print("Notebook written:", OUT)
print("Figures saved:", fig_i, "->", FIGDIR)
